export const data = {
  Marrakech: [
    {
      id: 1,
      img: "/images/arquitectura-desierto2.jpg",
      title: "Ciudades Imperiales",
      location: "Marrakech",
      days: "8",
    },
    {
      id: 2,
      img: "/images/essaouira4.jpg",
      title: "Desierto y Essaouira",
      location: "Marrakech",
      days: "7",
    },
    {
      id: 3,
      img: "/images/ouarzazat-2048x1516.jpg",
      title: "Desierto nómada y Ouarzazate",
      location: "Errachidia, Marrakech, Ouarzazate",
      days: "6",
    },
    {
      id: 4,
      img: "/images/88-2048x1152.jpg",
      title: "Marrakech y playas",
      location: "Marrakech",
      days: "5",
    },
    {
      id: 5,
      img: "/images/Marrakech_Jemaa-el-Fna.jpg",
      title: "Marrakech y desierto",
      location: "Marrakech",
      days: "3",
    },
    {
      id: 6,
      img: "/images/desierto-zagora.jpg",
      title: "Desierto de Zagora",
      location: "Marrakech, Ouarzazate",
      days: "2",
    },
    {
      id: 7,
      img: "/images/nomada_marrakech.jpg",
      title: "Marrakech y desierto nómada",
      location: "Fez,Marrakech",
      days: "4",
    },
  ],
  Ouarzazate: [
    {
      id: 8,
      img: "/images/desierto-zagora.jpg",
      title: "Desierto de Zagora",
      location: "Marrakech,Ouarzazate",
      days: "2",
    },
    {
      id: 9,
      img: "/images/ouarzazat-2048x1516.jpg",
      title: "Desierto nómada y Ouarzazate",
      location: "Errachidia, Marrakech, Ouarzazate",
      days: "6",
    },
  ],
  Errachidia: [
    {
      id: 10,
      img: "/images/ouarzazat-2048x1516.jpg",
      title: "Desierto nómada y Ouarzazate",
      location: "Errachidia, Marrakech, Ouarzazate",
      days: "6",
    },
  ],
  Fez: [
    {
      id: 11,
      img: "/images/essaouira4.jpg",
      title: "Chefchaouen, Fez y Desierto nómada",
      location: "Fez, Tanger",
      days: "6",
    },
    {
      id: 12,
      img: "/images/midelt.jpg",
      title: "Midelt y Desierto nómada",
      location: "Fez",
      days: "5",
    },
    {
      id: 13,
      img: "/images/nomada_marrakech.jpg",
      title: "Desierto nómada y Marrakech",
      location: "Fez, Marrakech",
      days: "4",
    },
    {
      id: 14,
      img: "/images/licensed-image-1.jpg",
      title: "Fez y Desierto nómada",
      location: "Fez",
      days: "3",
    },
  ],
  Casablanca: [
    {
      id: 15,
      img: "/images/Entrada-a-la-Mezquita-Hassan-II-con-visita-guiada-en-Casablanca.jpg",
      title: "Marruecos al completo",
      location: "Casablanca",
      days: "16",
    },
  ],
  Tanger: [
    {
      id: 11,
      img: "/images/essaouira4.jpg",
      title: "Chefchaouen, Fez y Desierto nómada",
      location: "Fez, Tanger",
      days: "6",
    },
  ],
};
